Repository Team537/RobotCode2025, pull requests merged in 2025-03, with the labels that each got.

#60 feature/narwhal elevator
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/narwhal/ManualNarwhalElevatorCommand.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalElevator.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalWrist.java
  src/main/java/frc/robot/util/NarwhalElevatorState.java
Labels: enhancement

#85 Release/v2.1.0
  .vscode/settings.json
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  vendordeps/PathplannerLib-2025.2.5.json
  vendordeps/Phoenix6-25.3.1.json
Labels: documentation, refactor

#92 feature/add general math classes
  src/main/java/frc/robot/util/math/Complex.java
  src/main/java/frc/robot/util/math/Matrix.java
Labels: enhancement, simulated

#91 feature/update oceanview data access
  src/main/java/frc/robot/subsystems/vision/OceanViewManager.java
  src/main/java/frc/robot/util/vision/ScoringLocation.java
Labels: enhancement, simulated

#97 feat(network): add port forwarding for photonvision2.local
  src/main/java/frc/robot/Robot.java
Labels: enhancement, rocket tested

#95 feat(vision): add time synchronization with Raspberry Pi
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/network/TimeSyncClient.java
  src/main/java/frc/robot/subsystems/vision/OceanViewManager.java
  src/main/java/frc/robot/util/vision/ScoringLocation.java
Labels: enhancement, simulated

#99 feature/setup odometry cameras
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
Labels: enhancement, robot tested - black

#106 Bugfix/pose fixes
  src/main/java/frc/robot/Constants.java
Labels: enhancement, simulated

#108 Release/v3.0.0
  .vscode/settings.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/DriveToPoseCommand.java
  src/main/java/frc/robot/commands/ManualDriveCommand.java
  src/main/java/frc/robot/commands/XboxManualDriveCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalAlgaeRemoveCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalClimbCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalCoralIntakeCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalCoralScoreCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalManualElevatorCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalManualWristCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalTransitPositionCommand.java
  src/main/java/frc/robot/network/TimeSyncClient.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalClimber.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalUpperAssembly.java
  src/main/java/frc/robot/util/NarwhalWristState.java
  src/main/java/frc/robot/util/autonomous/Alliance.java
  src/main/java/frc/robot/util/autonomous/Obstacle.java
  src/main/java/frc/robot/util/autonomous/StartingPosition.java
  src/main/java/frc/robot/util/field/AlgaeRemovalPosition.java
  src/main/java/frc/robot/util/field/CagePosition.java
  src/main/java/frc/robot/util/field/ReefScoringLocation.java
  src/main/java/frc/robot/util/math/Complex.java
  src/main/java/frc/robot/util/math/DeltaTime.java
  src/main/java/frc/robot/util/math/Matrix.java
  src/main/java/frc/robot/util/upper_assembly/UpperAssemblyFactory.java
Labels: enhancement, simulated

#110 Hotfix/center auto fix
  src/main/java/frc/robot/RobotContainer.java
Labels: bugfix

#109 fix(robot): update command for upper assembly intake
  src/main/java/frc/robot/RobotContainer.java
Labels: bugfix

#114 pref(drive): optimize update frequencies for gyroscope and motors
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
Labels: bugfix, simulated, refactor

#113 pref(drive): optimize update frequencies for gyroscope and motors
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
Labels: bugfix, simulated, refactor

#120 Hotfix/update wrist climber
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/narwhal/NarwhalManualClimberCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalManualWristCommand.java
Labels: enhancement, bugfix

#121 chore(build): update SpotBugs task to ignore failures
  build.gradle
Labels: refactor
