Repository Team537/RobotCode2025, pull requests merged in 2025-02, with the labels that each got.

#49 chore: update YAML indentation and action versions
  .github/workflows/gradle.yaml
Labels: bugfix

#50 GitHub/update actions to v4
  .github/workflows/gradle.yaml
Labels: bugfix

#53 docs: add detailed Javadoc comments to subsystems
  src/main/java/frc/robot/subsystems/squid/SquidClimber.java
  src/main/java/frc/robot/subsystems/squid/SquidManipulator.java
  src/main/java/frc/robot/util/SquidClimberPosition.java
Labels: documentation

#52 Release/v1.3.0
  src/main/deploy/pathplanner/navgrid.json
  src/main/deploy/pathplanner/paths/Example Path.path
  src/main/deploy/pathplanner/settings.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/squid/ManualSquidClimberCommand.java
  src/main/java/frc/robot/commands/squid/ManualSquidManipulatorCommand.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/subsystems/squid/SquidClimber.java
  src/main/java/frc/robot/subsystems/squid/SquidManipulator.java
  src/main/java/frc/robot/util/SquidClimberPosition.java
  vendordeps/Phoenix6-frc2025-latest.json
  vendordeps/REVLib.json
Labels: enhancement

#54 Feature/drive subsystem kraken rework
  src/main/java/frc/robot/Configs.java
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/ManualDriveCommand.java
  src/main/java/frc/robot/commands/XboxParkerManualDriveCommand.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/util/DrivingMotor.java
  src/main/java/frc/robot/util/TurningMotor.java
Labels: enhancement

#55 Release/v1.4.0
  src/main/java/frc/robot/Configs.java
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/ManualDriveCommand.java
  src/main/java/frc/robot/commands/XboxParkerManualDriveCommand.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/util/DrivingMotor.java
  src/main/java/frc/robot/util/TurningMotor.java
Labels: enhancement

#66 feature/add-driver-camera-support
  src/main/java/frc/robot/Robot.java
Labels: enhancement, Robot Tested - Black

#65 Feature/add central vision acess point
  .vscode/launch.json
  .vscode/settings.json
  build.gradle
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/Autos.java
  src/main/java/frc/robot/commands/ExampleCommand.java
  src/main/java/frc/robot/network/TCPSender.java
  src/main/java/frc/robot/network/UDPReceiver.java
  src/main/java/frc/robot/subsystems/ExampleSubsystem.java
  src/main/java/frc/robot/subsystems/vision/DataPacket.java
  src/main/java/frc/robot/subsystems/vision/OceanViewManager.java
  src/main/java/frc/robot/subsystems/vision/RobotPoseData.java
  src/main/java/frc/robot/subsystems/vision/odometry/PhotonVisionCamera.java
  src/main/java/frc/robot/subsystems/vision/odometry/VisionOdometry.java
  src/main/java/frc/utils/vision/ScoringLocation.java
Labels: enhancement, Rocket Tested

#73 chore: add bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#74 GitHub/add bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#72 refactor(upper_assembly): restructure UpperAssembly hierarchy
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalUpperAssembly.java
  src/main/java/frc/robot/subsystems/squid/SquidUpperAssembly.java
  src/main/java/frc/robot/subsystems/upper_assembly/UpperAssembly.java
  src/main/java/frc/robot/subsystems/upper_assembly/UpperAssemblyBase.java
  src/main/java/frc/robot/util/UpperAssemblyFactory.java
Labels: simulated, refactor

#67 fix: update default driving motor constant
  src/main/java/frc/robot/Constants.java
Labels: bugfix, robot tested - red

#69 fix: revert photonlib version to v2025.1.1
  vendordeps/photonlib.json
Labels: simulated, critical bugfix

#71 docs/clean up code
  .vscode/settings.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Main.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/ManualDriveCommand.java
  src/main/java/frc/robot/commands/XboxParkerManualDriveCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalManualClimberCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalManualIntakeOuttakeCommand.java
  src/main/java/frc/robot/commands/squid/ManualSquidClimberCommand.java
  src/main/java/frc/robot/commands/squid/ManualSquidManipulatorCommand.java
  src/main/java/frc/robot/network/TCPSender.java
  src/main/java/frc/robot/network/UDPReceiver.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/ExampleSubsystem.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalClimber.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalIntakeOuttake.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalWrist.java
  src/main/java/frc/robot/subsystems/vision/DataPacket.java
  src/main/java/frc/robot/subsystems/vision/OceanViewManager.java
  src/main/java/frc/robot/subsystems/vision/RobotPoseData.java
Labels: documentation, simulated

#68 docs/organize util folders
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/ManualDriveCommand.java
  src/main/java/frc/robot/commands/XboxParkerManualDriveCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalManualClimberCommand.java
  src/main/java/frc/robot/commands/squid/ManualSquidClimberCommand.java
  src/main/java/frc/robot/commands/squid/ManualSquidManipulatorCommand.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/LEDManager.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalClimber.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalIntakeOuttake.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalUpperAssembly.java
  src/main/java/frc/robot/subsystems/squid/SquidClimber.java
  src/main/java/frc/robot/subsystems/squid/SquidManipulator.java
  src/main/java/frc/robot/subsystems/squid/SquidUpperAssembly.java
  src/main/java/frc/robot/subsystems/upper_assembly/UpperAssembly.java
  src/main/java/frc/robot/subsystems/vision/OceanViewManager.java
  src/main/java/frc/robot/util/Elastic.java
  src/main/java/frc/robot/util/LEDs/LEDConfiguration.java
  src/main/java/frc/robot/util/autonomous/Alliance.java
  src/main/java/frc/robot/util/autonomous/AutonomousRoutine.java
  src/main/java/frc/robot/util/math/RateLimiter.java
  src/main/java/frc/robot/util/math/RateLimiter2d.java
  src/main/java/frc/robot/util/math/Vector2d.java
  src/main/java/frc/robot/util/swerve/DrivingMotor.java
  src/main/java/frc/robot/util/swerve/TurningMotor.java
  src/main/java/frc/robot/util/upper_assembly/ScoringHeight.java
  src/main/java/frc/robot/util/upper_assembly/UpperAssemblyFactory.java
  src/main/java/frc/robot/util/upper_assembly/UpperAssemblyType.java
  src/main/java/frc/robot/util/upper_assembly/narwhal/NarwhalClimberState.java
  src/main/java/frc/robot/util/upper_assembly/narwhal/NarwhalIntakeOuttakeState.java
  src/main/java/frc/robot/util/upper_assembly/squid/SquidClimberPosition.java
  src/main/java/frc/robot/util/vision/ScoringLocation.java
  src/main/java/frc/utils/DrivingMotor.java
  src/main/java/frc/utils/UpperSubstructure.java
Labels: documentation, simulated

#77 docs: update comments and add Javadoc for enums
  WPILib-License.md
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/vision/OceanViewManager.java
  src/main/java/frc/robot/util/LEDs/LEDConfiguration.java
  src/main/java/frc/robot/util/swerve/DrivingMotor.java
  src/main/java/frc/robot/util/swerve/TurningMotor.java
  src/main/java/frc/robot/util/upper_assembly/ScoringHeight.java
  src/main/java/frc/robot/util/upper_assembly/UpperAssemblyFactory.java
  src/main/java/frc/robot/util/upper_assembly/UpperAssemblyType.java
  src/main/java/frc/robot/util/vision/ScoringLocation.java
Labels: documentation, simulated

#76 release/v2.0.0
  .vscode/launch.json
  .vscode/settings.json
  build.gradle
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Main.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/Autos.java
  src/main/java/frc/robot/commands/ExampleCommand.java
  src/main/java/frc/robot/commands/ManualDriveCommand.java
  src/main/java/frc/robot/commands/XboxParkerManualDriveCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalManualClimberCommand.java
  src/main/java/frc/robot/commands/narwhal/NarwhalManualIntakeOuttakeCommand.java
  src/main/java/frc/robot/commands/squid/ManualSquidClimberCommand.java
  src/main/java/frc/robot/commands/squid/ManualSquidManipulatorCommand.java
  src/main/java/frc/robot/network/TCPSender.java
  src/main/java/frc/robot/network/UDPReceiver.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/ExampleSubsystem.java
  src/main/java/frc/robot/subsystems/LEDManager.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalClimber.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalIntakeOuttake.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalUpperAssembly.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalWrist.java
  src/main/java/frc/robot/subsystems/squid/SquidClimber.java
  src/main/java/frc/robot/subsystems/squid/SquidManipulator.java
  src/main/java/frc/robot/subsystems/squid/SquidUpperAssembly.java
  src/main/java/frc/robot/subsystems/upper_assembly/UpperAssembly.java
  src/main/java/frc/robot/subsystems/upper_assembly/UpperAssemblyBase.java
  src/main/java/frc/robot/subsystems/vision/DataPacket.java
  src/main/java/frc/robot/subsystems/vision/OceanViewManager.java
  src/main/java/frc/robot/subsystems/vision/RobotPoseData.java
  src/main/java/frc/robot/subsystems/vision/odometry/PhotonVisionCamera.java
  src/main/java/frc/robot/subsystems/vision/odometry/VisionOdometry.java
  src/main/java/frc/robot/util/DrivingMotor.java
  src/main/java/frc/robot/util/Elastic.java
  src/main/java/frc/robot/util/LEDs/LEDConfiguration.java
  src/main/java/frc/robot/util/TurningMotor.java
  src/main/java/frc/robot/util/autonomous/Alliance.java
  src/main/java/frc/robot/util/autonomous/AutonomousRoutine.java
  src/main/java/frc/robot/util/math/RateLimiter.java
  src/main/java/frc/robot/util/math/RateLimiter2d.java
  src/main/java/frc/robot/util/math/Vector2d.java
  src/main/java/frc/robot/util/swerve/DrivingMotor.java
  src/main/java/frc/robot/util/swerve/TurningMotor.java
  src/main/java/frc/robot/util/upper_assembly/ScoringHeight.java
  src/main/java/frc/robot/util/upper_assembly/UpperAssemblyFactory.java
  src/main/java/frc/robot/util/upper_assembly/UpperAssemblyType.java
  src/main/java/frc/robot/util/upper_assembly/narwhal/NarwhalClimberState.java
  src/main/java/frc/robot/util/upper_assembly/narwhal/NarwhalIntakeOuttakeState.java
  src/main/java/frc/robot/util/upper_assembly/squid/SquidClimberPosition.java
  src/main/java/frc/robot/util/vision/ScoringLocation.java
Labels: documentation, enhancement, refactor

#80 Feature/squid manipulator
  src/main/java/frc/robot/Constants.java
Labels: robot tested - red, refactor
