Repository Team537/RobotCode2025, pull requests merged in 2025-01, with the labels that each got.

#4 feat: add dashboard selectors for autonomous and alliance
  .gitignore
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/utils/Alliance.java
  src/main/java/frc/utils/AutonomousRoutine.java
Labels: enhancement

#6 fix: update WPILib and enhance folder names
  .gitignore
  build.gradle
  src/main/java/frc/robot/subsystems/vision/PhotonVisionCamera.java
Labels: documentation, enhancement

#7 feat: add autonomous and alliance selection alongside vision odometry
  .gitignore
  .vscode/settings.json
  build.gradle
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/ExampleCommand.java
  src/main/java/frc/robot/subsystems/vision/PhotonVisionCamera.java
  src/main/java/frc/utils/Alliance.java
  src/main/java/frc/utils/AutonomousRoutine.java
  test.txt
  vendordeps/Phoenix6-25.1.0.json
  vendordeps/REVLib-2025.0.0.json
  vendordeps/photonlib.json
Labels: documentation, enhancement

#13 Feature/abstract drive subsystem
  .gitignore
  simgui-ds.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/util/RateLimiter.java
  src/main/java/frc/robot/util/RateLimiter2d.java
  src/main/java/frc/robot/util/Vector2d.java
Labels: enhancement

#14 fix: improve code formatting and consistency
  src/main/java/frc/robot/subsystems/SwerveModule.java
Labels: bug

#17 Release/v1.1.0
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Main.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/Autos.java
  src/main/java/frc/robot/commands/ExampleCommand.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/ExampleSubsystem.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/util/RateLimiter.java
  src/main/java/frc/robot/util/Vector2d.java
  src/main/java/frc/utils/Alliance.java
  src/main/java/frc/utils/AutonomousRoutine.java
Labels: enhancement

#16 Release/v1.1.0
  .gitignore
  simgui-ds.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Main.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/Autos.java
  src/main/java/frc/robot/commands/ExampleCommand.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/ExampleSubsystem.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/util/RateLimiter.java
  src/main/java/frc/robot/util/RateLimiter2d.java
  src/main/java/frc/robot/util/Vector2d.java
  src/main/java/frc/utils/Alliance.java
  src/main/java/frc/utils/AutonomousRoutine.java
Labels: enhancement

#20 style: improve code formatting and add documentation
  .vscode/settings.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/util/RateLimiter.java
  src/main/java/frc/robot/util/RateLimiter2d.java
  src/main/java/frc/robot/util/Vector2d.java
  src/main/java/frc/utils/Alliance.java
  src/main/java/frc/utils/AutonomousRoutine.java
Labels: documentation

#34 chore: disable XML report generation in PMD task
  build.gradle
Labels: bug

#38 feat: unify vision and drive odometry
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/vision/PhotonVisionCamera.java
  src/main/java/frc/robot/subsystems/vision/VisionOdometry.java
  vendordeps/photonlib.json
Labels: enhancement

#39 Feature/narwhal intake outtake
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalIntakeOuttake.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalIntakeOuttakeState.java
Labels: enhancement

#43 style: improve documentation
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/LEDManager.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalIntakeOuttake.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalIntakeOuttakeState.java
  src/main/java/frc/robot/subsystems/vision/PhotonVisionCamera.java
  src/main/java/frc/robot/subsystems/vision/VisionOdometry.java
  src/main/java/frc/utils/LEDs/LEDConfiguration.java
  src/main/java/frc/utils/LEDs/LEDManager.java
Labels: documentation

#45 style: reformat comments and add class documentation
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Main.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalWrist.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalWristState.java
Labels: documentation

#46 Release/v1.2.0
  .vscode/settings.json
  src/main/deploy/pathplanner/settings.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Main.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/LEDManager.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalIntakeOuttake.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalIntakeOuttakeState.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalWrist.java
  src/main/java/frc/robot/subsystems/narwhal/NarwhalWristState.java
  src/main/java/frc/robot/subsystems/vision/PhotonVisionCamera.java
  src/main/java/frc/robot/subsystems/vision/VisionOdometry.java
  src/main/java/frc/robot/util/RateLimiter.java
  src/main/java/frc/robot/util/RateLimiter2d.java
  src/main/java/frc/robot/util/Vector2d.java
  src/main/java/frc/utils/Alliance.java
  src/main/java/frc/utils/Autonomous/Alliance.java
  src/main/java/frc/utils/Autonomous/AutonomousRoutine.java
  src/main/java/frc/utils/AutonomousRoutine.java
  src/main/java/frc/utils/LEDs/LEDConfiguration.java
  vendordeps/photonlib.json
Labels: enhancement
